### ISSUE TITLE
任意高度的全屏布局

### ISSUE THREAD

**Issue by liuxiaodeng** [liuxiaodeng/Infinite-css#2]
全屏布局，你第一想到的就是 ```height: 100%```，可是这里面有一个坑：

就是在高度设置 100% 的时候，父级元素的高度必须设定 100%，否则是无效的。

但是如果涉及到比较深层嵌套时，是一件非常麻烦的事情。比如我们会经常见到这样的代码：

```css
html,body {
  height: 100%;
}
```

目的就是为了子元素可以设定 ```height: 100%```。这种方式的缺点就是嵌套层级深时，带来维护的麻烦。

今天介绍一种方法可以让元素的 ```height: 100%``` 产生效果。那就是给元素加个绝对定位属性。

```vue
<template>
<div class="box">
  无高度父元素
  <div class="child"></div>
</div>
</template>
<style>
.box {
  position: relative;
  padding: 100px;
  width: 300px;
  color: #3eaf7c;
}
.child {
  position: absolute;
  width: 100%;
  height: 100%;
  top: 0;
  left: 0;
  background-color: rgba(0,0,0,.5);
}
</style>
```

当然除此之外，我们还可以用另外一种方式实现相同效果。

```css
.child {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: rgba(0,0,0,.5);
}
```

大家可以想象一下，在什么场景下使用此方法比较好。其实页面的 loading 非常适合这种方式实现。不仅仅是全局的 loading，更适合某个局部元素的 loading。比如表格刷新时，在表格中加入loading。

这是方式的好处在于，我们不用关心元素的高度，适用性非常强。
[查看效果](https://liuxiaodeng.github.io/css-tip/any-height-full.html)

---
更多优质文章关注微信公众号：六小登登，加我微信，拉你进入优质前端交流群。来这里一起交流，一起进步。
